version: '3'
services:
  mysql:
   build: ./docker/mysql
   environment:
    MYSQL_ROOT_PASSWORD: admin123
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  app:
    build: ./docker/java
    environment:
        title: Hand
        description: com.Hand
        language_id: 1
    restart: always

